#!/usr/bin/env bash

query_w="select distinct user_name from maia.mailaddr as a \
    join maia.wblist on a.id = maia.wblist.sid \
	join maia.maia_users on maia.maia_users.id = maia.wblist.rid \
	where maia.maia_users.id not in (1, 8) and wb='W'"

query_b="select distinct user_name from maia.mailaddr as a \
    join maia.wblist on a.id = maia.wblist.sid \
	join maia.maia_users on maia.maia_users.id = maia.wblist.rid \
	where maia.maia_users.id not in (1, 8) and wb='B'"

# shellcheck disable=2207
white=($(printf "%s" "${query_w}" | mysql -N))

# shellcheck disable=2207
black=($(printf "%s" "${query_b}" | mysql -N))

load_white () {
	for ((i=0;i<${#white[@]};i++))
	do
		echo "${white[i]}"
	done
}

load_black () {
	for ((i=0;i<${#black[@]};i++))
	do
		echo "${black[i]}"
	done
}
# shellcheck disable=2207
dodidadudadi () {
eval "$1"+="($(grep -E "$(sed ':a;N;$!ba;s/\n/|/g' \
    <(load_"${2}"))" \
	<(curl -ks \
	    -H "$(cat CSFR)" \
		-b "$(cat ticket)" \
		-XGET https://62.116.163.165:8006/api2/json/config/ruledb/who \
		    | jq -jr '.data[] \
			    | select (.name | contains(".${3}")) \
				| .id,",",.name,"\n"')\
))"
}

dodidadudadi blacko black blacklist
dodidadudadi whitos white whitelist

load_whitos () {
	for ((i=0;i<${#whitos[@]};i++))
	do
		id=$(echo ${whitos[i]} | awk -F "," '{print $1}')
		user=$(echo ${whitos[i]} | awk -F "," '{print $2}' | sed 's#.whitelist##g')
		
		for addr in $(echo "select email from maia.mailaddr as a join maia.wblist on a.id = maia.wblist.sid join maia.maia_users on maia.maia_users.id = maia.wblist.rid where wb='W' and user_name='$user';" | mysql --skip-column-names)
		do
			if [ -z $(grep ^@ <(echo $addr)) ]
			then
				curl -ks -H "`cat CSFR`" -b "`cat ticket`" -d "email=$addr" -XPOST https://62.116.163.165:8006/api2/json/config/ruledb/who/$id/email && echo -n ${whitos[i]} && echo -n " " && echo $addr
			elif [ ! -z $(grep ^@ <(echo $addr)) ]
			then
				curl -ks -H "`cat CSFR`" -b "`cat ticket`" -d "domain=$( echo $addr | sed 's/^@//')" -XPOST https://62.116.163.165:8006/api2/json/config/ruledb/who/$id/domain && echo -n ${whitos[i]} && echo -n " " && echo $addr
			fi

		done

	done
}

load_blacko () {
	for ((i=0;i<${#blacko[@]};i++))
	do
		id=$(echo ${blacko[i]} | awk -F "," '{print $1}')
		user=$(echo ${blacko[i]} | awk -F "," '{print $2}' | sed 's#.blacklist##g')

		for addr in $(echo "select email from maia.mailaddr as a join maia.wblist on a.id = maia.wblist.sid join maia.maia_users on maia.maia_users.id = maia.wblist.rid where wb='B' and user_name='$user';" | mysql --skip-column-names)
		do
			if [ -z $(grep ^@ <(echo $addr)) ]
			then
				curl -ks -H "`cat CSFR`" -b "`cat ticket`" -d "email=$addr" -XPOST https://62.116.163.165:8006/api2/json/config/ruledb/who/$id/email && echo -n ${whitos[i]} && echo -n " " && echo $addr
			elif [ ! -z $(grep ^@ <(echo $addr)) ]
			then
				curl -ks -H "`cat CSFR`" -b "`cat ticket`" -d "domain=$( echo $addr | sed 's/^@//')" -XPOST https://62.116.163.165:8006/api2/json/config/ruledb/who/$id/domain && echo -n ${blacko[i]} && echo -n " " && echo $addr

			fi
		done

	done
}


load_whitos
#load_blacko
